food/urls.py
from . import views
from django.urls import path
app_name = 'food'
urlpatterns = [
    # path('',views.index,name = 'index'),
    path('',views.IndexClassView.as_view(),name = 'index'),
    # path('<int:item_id>/',views.detail,name = 'detail'),
    path('<int:pk>/',views.FoodDetail.as_view(),name = 'detail'),
    path('item/',views.item,name = 'item'),
    # path('add',views.create_item,name='create_item'),
    path('add',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:id>',views.update_item,name='udate_item'),
    path('delete/<int:id>/',views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name = "users/login.html"),name = 'login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name = "users/logout.html"),name = 'logout'),
    path('profile/',user_views.profilepage,name='profile'),
    
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self) :
        return self.item_name
    user_name = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
      return reverse("food:detail", kwargs={"pk": self.pk})

    

users/models.py
from django.db import models


from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
# Create your models here.

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from django.views.generic.edit import CreateView
# Create your views here.
def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list' : item_list,
    }
    # return HttpResponse(template.render(context,request))
    return render (request,'food/index.html',context)

# this works same as above index function only difference is that it is class based inbuilt view
class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'



def item(request):
    return HttpResponse('<h1>this is an item view</h1>')

# def detail(request,item_id):
#     return HttpResponse ("This is item no/id: %s"%item_id)
def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'



def create_item(request):
    form = ItemForm(request.POST or None)
    context = {
        'form':form,
    }
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render (request,'food/item-form.html',context)

# this is class view of create_item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request,id):
    item = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None,instance=item)
    context = {
        'item':item,
        'form':form,
    }
    if form.is_valid():
        form.save()
        return redirect ('food:index')
    return render (request,'food/item-form.html',context)

def delete_item(request,id):
    item = Item.objects.get(id=id)
    # context = {
    #     'item':item,
    # }
    if request.method=="POST":
        item.delete()
        return redirect ('food:index')
    return render (request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . forms import RegisterForm  
def register(request):
    if request.method =='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username},your account is created')
            return redirect ('login')
    else:
        form = RegisterForm()  
    return render(request,'users/register.html',{'form':form})
# Create your views here.
@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->

<html>
  <head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="#" class="navbar-brand">FoodApp</a>
      <div class="navbar">
        <a
          class="nav-item mx-2 nav-link text-light"
          href="{% url 'food:create_item' %}"
          >Add Item
        </a>
        <a class="nav-item mx-2 nav-link text-light" href="#">Delete Item </a>
        <a class="nav-item mx-2 nav-link text-light" href="#">View Item </a>
       
        {% if user.is_authenticated%}
        <a href = "{% url "logout"%}" class ="nav-item mx-2 nav-link text-light"> logout </a>
        <a href = "{% url "profile"%}" class ="nav-item mx-2 nav-link text-light"> profile </a>
        {%else%}
        <a href = "{% url "register" %}" class="nav-item mx-2 nav-link text-light">register</a>
        <a href = "{% url "login" %}" class="nav-item mx-2 nav-link text-light"> login</a>
        {%endif%}
        
      </div>
    </nav>
    {% if messages %} 
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {%endfor%}
     {% endif %} 
     {% block body %} {% endblock %}
  </body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html'%}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    {% block body %}
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img height="300px" src="{{object.item_image}}" />
        </div>
        <div class="col-md-6">

          {% comment %} <h1>{{item.item_name}}</h1>
          <h1>{{item.item_desc}}</h1>
          <h1>${{item.item_price}}</h1> {% endcomment %}
          {% comment %} above for function based call and below for class based call {% endcomment %}
          <h1>{{object.item_name}}</h1>
          <h1>{{object.item_desc}}</h1>
          <h1>${{object.item_price}}</h1>
          <a href="{% url 'food:delete_item' item.id %}"><button type="button" class="btn btn-outline-danger">Delete</button></a>
        </div>
      </div>
    </div>
    {% endblock %} 
  </body>
</html>

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        
    </head>
    <body>
         
        {% comment %} <h1> This is just a template </h1> {% endcomment %}
     {% block body %}
        {% for item in item_list %}
       
        <div class = "row">
            <div class = "col-md-5 offset-md-2">
                <img class = "card" height = "150px"  width = "200px" src = "{{item.item_image}}">
            </div>
            <div class = "col-md-3">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6> ${{item.item_price}}</h6>
                <h6>{{item.user_name}}</h6>
            </div>
            <div class = "col-md-2">
            <a href = "{% url 'food:detail' item.id%}" class = "btn btn-success"> details </a>
            </div>
        </div>
        {% endfor %}
    {% endblock %}
    <ul>
        <li> <a href = "{% url 'food:detail' item.id%}">{{item.id}}---{{item.item_name}} </a> </li>
        {% comment %} <li> <a href = "/food/{{item.id}}">{{item.id}}---{{item.item_name}} </a> </li> {% endcomment %}
    </ul> 
        <script src="" async defer></script>
    </body>
</html>

food/templates/food/item-delete.html
<div style="background-color:powderblue;" >
<form method = "POST">
    {% csrf_token %}
    <h2 style = "text-align:center"> are you sure that you want to delete item {{item.item_name}} </h2>
    <div style = "text-align:center" class = "btn btn-primary"><button type = "submit"> confirm </button></div>


</form>

</div>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class = "container">
    <div class = "row">
        <div class = "col-md-4 offset-md-4">
            <div class = "card">
                <div class = "card-header text-white bg-info">
                    <div class = "card-title">
                        Add Item
                    </div>
                </div>

                <div class = "card-body">
                    <form method = "POST">
                        {%csrf_token%}
                        {% for field in form %}
                        <div class = "form-group">
                        {{field.name}}
                        </br>
                        {{field}}
                        </div>
                        {% endfor %}
                    </br>
                        <button  class ="btn-info" type = "submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
<div class = "container">
    <div class = "row">
        <div class = "col-md-4 offset-md-4">
            <div class = "card">
                <div class = "card-header text-white bg-info">
                    <div class = "card-title">
                        Login
                    </div>
                </div>

                <div class = "card-body">
                    <form method = "POST">
                        {%csrf_token%}
                        {% for field in form %}
                        <div class = "form-group">
                        {{field.name}}
                        </br>
                        {{field}}
                        </div>
                        {% endfor %}
                    </br>
                        <button  class = "btn-info" type = "submit">Login </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

{% comment %} <form method = "POST">
    {%csrf_token%}
    {{form}}
    <button type = "submit">Login </button>
</form> {% endcomment %}

users/templates/users/logout.html
<h2>You have been logout! successfully</h2>

users/templates/users/profile.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body style="background-color:powderblue">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div>
        <h1 > {{user.username}} </h1>
        <img
      class="rounded-circle account-img"
      height = '300px'
      src="{{ user.profile.image.url }}"
    />
        </div>
        <script src="" async defer></script>
    </body>
</html>

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}
<div class = "container">
    <div class = "row">
        <div class = "col-md-4 offset-md-4">
            <div class = "card">
                <div class = "card-header text-white bg-info">
                    <div class = "card-title">
                        Sign Up
                    </div>
                </div>

                <div class = "card-body">
                    <form method = "POST">
                        {%csrf_token%}
                        {% for field in form %}
                        <div class = "form-group">
                        {{field.name}}
                        </br>
                        {{field}}
                        </div>
                        {% endfor %}
                    </br>
                        <button  class ="btn-info" type = "submit">Sign Up </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}